#!/usr/bin/env python

import sys
import re

word_re_sub = re.compile(r'[^ \n]+').sub

def words_path(path):
    with open(path) as fp:
        return set(fp.read().split('\n'))

def main(args=sys.argv[1:]):
    words = words_path(args[0] if args else '/usr/share/dict/words')

    def replace(match):
        word = match.group(0)
        if word.lower() not in words:
            return '<' + word + '>'
        return word

    sys.stdout.write(word_re_sub(replace, sys.stdin.read()))

if __name__ == "__main__":
    main()
